# Generated by Django 3.1.4 on 2021-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(default='รหัสลับ', max_length=10),
        ),
    ]
