# Generated by Django 3.1.4 on 2021-01-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210111_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='firstname',
        ),
    ]
