# Generated by Django 3.1.4 on 2021-02-10 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210202_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('empid', models.CharField(default='00000', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default='ชื่อเล่น', max_length=30)),
                ('position', models.CharField(default='ตำแหน่ง', max_length=20)),
                ('position_level', models.CharField(default='ระดับ', max_length=5)),
                ('department_name', models.CharField(default='สังกัด', max_length=50)),
                ('department_code', models.CharField(default='รหัสSAP', max_length=50)),
                ('workage', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('point', models.IntegerField(default=0, null=True)),
                ('yollow_card', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Progress', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='star',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.profile')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.star')),
            ],
        ),
    ]
